### ISSUE TITLE
Choice/Case Juniper EX VLAN example does not generate proper XML

### ISSUE THREAD

**Issue by henderiw** [sdcio/data-server#155]
```
     - name: ge-0/0/1
            unit:
            - name: "0"
              family:
                ethernet-switching:
                 interface-mode: trunk
                 vlan:
                   members:
                   - VLAN100
                   - VLAN200
                   - VLAN300
```

Also if I configure it manually, the following is the output of show | display xml   

```
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/23.2R1.15/junos">
    <configuration junos:changed-seconds="1719953971" junos:changed-localtime="2024-07-02 20:59:31 UTC">
            <interfaces>
                <interface>
                    <name>ge-0/0/1</name>
                    <unit>
                        <name>0</name>
                        <family>
                            <ethernet-switching>
                                <vlan>
                                    <members>VLAN100</members>
                                    <members>VLAN200</members>
                                </vlan>
                            </ethernet-switching>
                        </family>
                    </unit>
                </interface>
            </interfaces>
    </configuration>
    <cli>
        <banner>[edit]</banner>
    </cli>
</rpc-reply>
```
