### ISSUE TITLE
NETCONF RPC Error - BGP License Requirement

### ISSUE THREAD

**Issue by infinitydon** [sdcio/data-server#158]
I ecnountered the following error when I try to create a configuration that is related to BGP in vJunos-lab router, this should be reported as a warning and not come up as an error though the configuration was applied correctly in the router.

```
Status:
  Conditions:
    Last Transition Time:  2024-08-02T15:59:42Z
    Message:               rpc error: code = Unknown desc = operation error from input '<?xml version="1.0" encoding="UTF-8"?><rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="438"><commit/></rpc>'. matched error sub-string '<rpc-error>
<error-severity>warning</error-severity>
<source-daemon>
mgd
</source-daemon>
<error-path>
[edit routing-instances VRF-Example protocols]
</error-path>
<error-info>
<bad-element>
bgp
</bad-element>
</error-info>
<error-message>
requires 'bgp' license
</error-message>
</rpc-error>'. full output: ''
    Reason:  Failed
    Status:  False
    Type:    Ready
```

Though after some minutes the error goes away.

Sample config used:

```
apiVersion: config.sdcio.dev/v1alpha1
kind: Config
metadata:
  name: intent1-junos
  namespace: default
  labels:
    config.sdcio.dev/targetName: junos-central
    config.sdcio.dev/targetNamespace: default
spec:
  priority: 10
  config:
  - path: /
    value:
      configuration:
        vlans:
          vlan:
          - name: VLAN100
            vlan-id: 100
            l3-interface: irb.100
          - name: VLAN200
            vlan-id: 200
            l3-interface: irb.200
          - name: VLAN300
            vlan-id: 300
            l3-interface: irb.300
        interfaces:
          interface:
          - name: irb
            unit:
            - name: "100"
              family:
                inet:
                  address:
                  - name: "192.168.1.1/24"
            - name: "200"
              family:
                inet:
                  address:
                  - name: "192.168.2.1/24"
            - name: "300"
              family:
                inet:
                  address:
                  - name: "192.168.3.1/24"
          - name: ge-0/0/1
            unit:
            - name: "0"
              family:
                ethernet-switching:
                 interface-mode: trunk
                 vlan:
                 - members: 
                   - VLAN100
                   - VLAN200
                   - VLAN300
        routing-instances:
          instance:
          - name: VRF-Example
            instance-type: vrf
            interface:
            - name: irb.100
            - name: irb.200
            - name: irb.300
            route-distinguisher:
              rd-type: "100:1"
            vrf-target: 
              community: "target:100:1"            
            protocols:
              bgp:
                group:
                - name: internal
                  type: internal
                  local-as:
                    as-number: 65001
                  neighbor:
                  - name: 192.168.1.2
                    peer-as: 65001
```

Thanks
